# This is an appspec.yml template file for use with an EC2/On-Premises deployment in AWS CodeDeploy.
# For help completing this file, see the "AppSpec File Reference" in the  
#   "AWS CodeDeploy User Guide" at
#   https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: linux 

files:
  - source: ./brown.zip
    destination: /tmp

hooks:

# During the BeforeInstall deployment lifecycle event, run the commands 
#   in the script specified in "location".
  BeforeInstall:
    - location: /tmp/unzip.sh
      timeout:
      runas:

# reference: https://docs.aws.amazon.com/codedeploy/latest/userguide/application-revisions-appspec-file.html?icmpid=docs_acd_console
