######### STEPS
## 1- Run  `docker-compose -f docker-compose-splunk.yml up`
## 2- Then login to Splunk -> Setting -> Inputs -> HTTP Event Collector -> create a new token via Splunk UI
## 3 Add this newly created token to the HEC
## 4- Run other compose file `docker-compose up`


version: "3"

services:

  nginx:
    # replace username/repo:tag with your name and image details
    build: ./apiGateway/nginx
    container_name: nginx-node
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "7777:7777"
    networks:
      - back-end
      - front-end
    depends_on:
      - gateway
      - crud
      - search
    logging:
      driver: splunk
      options:
        splunk-url: "https://127.0.0.1:8088"
        splunk-token: "876557C5-28CA-44A1-9388-76211F0C1634"
        splunk-insecureskipverify: "true"

  gateway:
    # replace username/repo:tag with your name and image details
    build: ./apiGateway
    container_name: gateway-node
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "9000:9000"
    env_file:
      gateway_db.env
    networks:
      - front-end
      - back-end
    depends_on:
      - crud
      - search
      - gatewaydb

  crud:
    # replace username/repo:tag with your name and image details
    build: ./crudService
    container_name: crud-node
    # image: crudsvc
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5001:5001"
    # environment:
    #   CRUD_DB_HOST: cruddb:3306
    env_file:
      crud_db.env
    depends_on:
      - cruddb
    networks:
      - front-end
      - back-end

  search:
    # replace username/repo:tag with your name and image details
    build: ./searchService
    container_name: search-node
    # image: searchsvc
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5002:5002"
    networks:
      - front-end
      - back-end

  cruddb:
    image: mysql:5.7
    # volumes:
    #   - db_data:/var/lib/mysql
    container_name: cruddb-node
    restart: always
    env_file:
      crud_db.env
    networks:
      - back-end

  gatewaydb:
    image: mysql:5.7
    container_name: gatewaydb-node
    restart: always
    env_file:
      gateway_db.env
    networks:
      - back-end

networks:
  front-end:
  back-end:
