version: "3"

services:

  nginx:
    # replace username/repo:tag with your name and image details
    build: ./apiGateway/nginx
    container_name: nginx-node
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "7777:7777"
    networks:
      - back-end
      - front-end
    depends_on:
      - gateway
      - crud
      - search


  gateway:
    # replace username/repo:tag with your name and image details
    build: ./apiGateway
    container_name: gateway-node
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "9000:9000"
    networks:
      - front-end
      - back-end
    depends_on:
      - crud
      - search

  crud:
    # replace username/repo:tag with your name and image details
    build: ./crudService
    container_name: crud-node
    # image: crudsvc
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5001:5001"
    networks:
      - front-end
      - back-end


  search:
    # replace username/repo:tag with your name and image details
    build: ./searchService
    container_name: search-node
    # image: searchsvc
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5002:5002"
    networks:
      - front-end
      - back-end

networks:
  front-end:
  back-end:
