# To run this docker-compose -f docker-compose-splunk.yml up


version: '2'
services:
  splunk:
    image: store/splunk/enterprise:6.5.2-monitor
    hostname: splunkenterprise
    container_name: splunk-node
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_ADD: tcp 1514
      SPLUNK_USER: root
    volumes:
      - /var/lib/docker/containers:/host/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes:
      - /opt/splunk/etc
      - /opt/splunk/var
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"